platform :ios, ’9.0’

target 'myVideos' do
  use_frameworks!

  # Pods for myVideos
  pod 'Gloss', '~> 1.2'
  pod 'Alamofire', '~> 4.4'

  target 'myVideosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'myVideosUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
